chart_table/tutorials/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

chart_table/main/models.py
from django.db import models

GATE1, GATE2 = range(2)
GATE = (
    (GATE1, 'GATE1'),
    (GATE2, 'GATE2')
)

CHECKIN, CHECKOUT = range(2)
STATUS = (
    (CHECKIN, 'CHECKIN'),
    (CHECKOUT, 'CHECKOUT'),
)


class Parkir(models.Model):
    id_card = models.CharField('ID Card', max_length=50)
    gate = models.PositiveSmallIntegerField('Gate', choices=GATE, default=GATE1)
    status = models.PositiveSmallIntegerField('Status', choices=STATUS, default=CHECKIN)
    tanggal = models.DateField('tanggal')
    jam = models.TimeField('jam')
    biaya = models.IntegerField('biaya', choices=list(zip(range(1000, 11000, 1000), range(1000, 11000, 1000))), null=True, blank=True)

    def __unicode__(self):
        return self.id_card

    class Meta:
        verbose_name = ('Parkir')

chart_table/main/views.py
from django.shortcuts import render

chart_table/main/templates/change_list_graph.html
{% extends "admin/change_list.html" %}
{% load staticfiles %}
{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                position: 'left'
            },
            title: {
                display: true
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        window.onload = function () {
            var ctx = document.getElementById("gate-chart");
            {% regroup cl.queryset|dictsort:"gate" by get_gate_display as gate_list %}
            var lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for gate in gate_list %}'{{ gate.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for gate in gate_list %}'{{ gate.list|length }}',{% endfor %}],
                        backgroundColor: [{% for gate in gate_list %}randomColorGenerator(),{% endfor %}]
                    }]
                },
                options: options
            });
            ctx = document.getElementById("tanggal-chart");
            {% regroup cl.queryset|dictsort:"tanggal" by tanggal as tanggal_list %}
            lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for tanggal in tanggal_list %}'{{ tanggal.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for tanggal in tanggal_list %}'{{ tanggal.list|length }}',{% endfor %}],
                        backgroundColor: [{% for tanggal in tanggal_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
        }
    </script>
{% endblock %}
{% block content %}
    <h1> graphs </h1>
    <hr>
    <div class="row">
        <div class="col-sm-4">
            <canvas id="gate-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
            <canvas id="tanggal-chart" style="width: 100px !important;"></canvas>
        </div>
    </div>

    {{ block.super }}
{% endblock %}